# -*- coding: utf-8 -*-
"""
/***************************************************************************
 SeisPosImport
                                 A QGIS plugin
 This plugin imports Seismic Positioning or Navigation data from various formats such as P1/11 (P111), P1/90 (P190), SPS.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2020-06-30
        copyright            : (C) 2020 by Gurpreet Singh
        email                : gurpreet.s.singh@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load SeisPosImport class from file SeisPosImport.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .seismic_importer import SeisPosImport
    return SeisPosImport(iface)
